name: Github Pages

# By default, runs if you push to master. keeps your deployed app in sync with master branch.
on:
  push:
    branches:
      - main
      - golang
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: dist
        run: make deploy
        