name: Github Pages

# By default, runs if you push to master. keeps your deployed app in sync with master branch.
on:
  push:
    branches:
      - main
      - golang
# to only run when you do a new github release, comment out above part and uncomment the below trigger.
# on:
#   release:
#     types:
#       - published

permissions:
  contents: write # for committing to gh-pages branch.

jobs:
  build-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: gogio
        uses: go install gioui.org/cmd/gogio@latest
      - name: dist
        run: make dist
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          # this option will not maintain any history of your previous pages deployment
          # set to false if you want all page build to be committed to your gh-pages branch history
          single-commit: true